### ISSUE TITLE
Failed infection test if bypass-final is enabled

### ISSUE THREAD

**Issue by Pablossoo** [dg/bypass-finals#29] opened 2021-09-23 07:37 UTC
Hello, I am using the library for infection testing https://infection.github.io/guide/ and if the bypass-final library is enabled the infections are not working as expected - the coverage test is not working properly.
example;
the case where bypass is disabled;
100% coverage of infection

the case where the bypass is enabled;
20-30% coverage.

Could you please take a look at what might be wrong?

**Comment by JanTvrdik** [comment] 2021-09-23 08:32
https://github.com/dg/bypass-finals/issues?q=infection

**Comment by dkarlovi** [comment] 2022-09-02 10:03
Duplicate of #9.

**Comment by dkarlovi** [comment] 2022-09-13 14:58
#9 was closed, this can be closed too AFAIK.

**Closed** 2022-09-13 15:21 UTC
